return {
    'leissa/nvim-tex',
    ft = { "tex", "plaintex", "latex" },
    opts = {
        qf = {
            ignore_filters = {
                "\\vspace should only be used",
                "A possible image without description",
                "Marginpar on page",
                "Overfull",
                "Underfull",
                'Missing ".*" in',
                "todonotes Warning",
                "Font shape.*",
                "cannot apply log",
                "in font nullfont",
                "Size substitutions",
                "Some font shapes",
                "Columns might not be balanced",
                "Some images may lack description",
                "ACM keywords are mandatory",
                "ACM reference format is mandatory",
                "CCS concepts are mandatory",
                "empty address in",
                "empty publisher in",
                "page numbers missing",
                "empty school",
            },
        },
        imaps = { leader = 'ö' },
    },
}
